version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - SMTP_HOST=mailserver
      - SMTP_PORT=1025
      - SMTP_PASS=password
      - SMTP_USER=admin
      - QUIZ_DATA_DIR=/opt/data
      - BACKEND_URL=http://localhost/api
      - BASE_URL=http://localhost
    volumes:
      - ./data:/opt/data
    ports:
      - "80:80"
    networks:
      - app-network

  mailserver:
    image: maildev/maildev
    container_name: mailserver
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge