version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./docker:/docker
    ports:
      - "80:80"

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
