version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - SMTP_HOST=127.0.0.1
      - SMTP_PORT=2525
      - SMTP_PASS=password
      - SMTP_USER=admin
      - QUIZ_DATA_DIR=/opt/data
      - BACKEND_URL=http://localhost/api
      - VITE_BACKEND_URL=http://localhost/api
    volumes:
      - ./data:/opt/data
    ports:
      - "80:80"
    networks:
      - app-network

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge