/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./src/components/Admin.vue')['default']
    AnswerInput: typeof import('./src/components/UserQuizAnswer.vue')['default']
    CreateQuiz: typeof import('./src/components/CreateQuiz.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    QuestionOutput: typeof import('./src/components/QuestionOutput.vue')['default']
    Quiz: typeof import('./src/components/Quiz.vue')['default']
    Registration: typeof import('./src/components/Registration.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolveQuiz: typeof import('./src/components/SolveQuiz.vue')['default']
    StudentInput: typeof import('./src/components/UserQuizRegistration.vue')['default']
    UserQuizAnswer: typeof import('./src/components/UserQuizAnswer.vue')['default']
    UserQuizRegistration: typeof import('./src/components/UserQuizRegistration.vue')['default']
  }
}
