/* tslint:disable */
/* eslint-disable */
/**
 * Quiz App API
 * Dies ist die API-Beschreibung für die Quiz-App API. Sie Bestandteil der Projektabgabe im Fach Projekt: Web-Entwicklung
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

